app_config:
  package_name: "modelo-prediccion-tierras"
  train_data_file: "model/datasets/df_depuradov2.csv"
  test_data_file: "model/datasets/df_depuradov2.csv"
  pipeline_save_file: "modelo-prediccion-tierras-output"

model_configs:
  random_forest: "./model_configs/random_forest.yml"
  logistic_regression: "./model_configs/logistic_regression.yml"