target: "rango_precios_var_dependiente"
version: "1.0.0"
features:
  - municipio
  - departamen
  - categoria_mtv11
  - TIPO_ECOSI
  - GRADO_TRAN
  - GRAN_BIOMA
  - BIOMA_PREL
  - BIOMA_IAvH
  - ECOS_SINTE
  - ECOS_GENER
  - UNIDAD_SIN
  - CLIMA
  - PAISAJE
  - RELIEVE
  - SUELOS
  - AMB_EDAFOG
  - DESC_AMB_E
  - COBERTURA
  - ANFIBIOS
  - AVES
  - MAGNOLIOPS
  - MAMIFEROS
  - REPTILES
  - NOMAH
  - NOMZH
  - NOMSZH
  - IPHE_CATEGORIA
  - IUEA_CATEGORIA
  - HHV2020
  - HHA_2020
  - IARC_CATEGORIA
  - IUA_MEDIO_CAREGORIA
  - IUA_sECO_CATEGORIA
  - CATIACAL_M
  - CIACAL_S
  - cat
  - IVH_MEDIO_CATEGORIA
  - IVH_SECO_CATEGORIA
  - S_UC_FASE
  - OTRAS_FA_1
  - PENDIENT_1
  - EROSION_1
  - S_CLIMA
  - CLIMA_1
  - S_PAISAJE
  - PAISAJE_1
  - TIPO_RELIE
  - MATERIAL_P
  - SUBGRUPO
  - PERFILES
  - PORCENTAJE
  - PROFUNDIDA
  - TEXTURA
  - FERTILIDAD
  - ACIDEZ
  - DRENAJE
  - HUMEDAD
  - ALUMINIO
  - SALINIDAD_1
  - SODICIDAD
  - SATURACION
  - CALCAREO
  - Significad
  - layer
  - codigo
  - FA
test_size: 0.25
random_state: 42
solver: "lbfgs"
max_iter: 100
qual_vars:
  - rango_precios_var_dependiente
categorical_vars:
  - municipio
  - departamen
  - categoria_mtv11
  - cod_precios
  - TIPO_ECOSI
  - GRADO_TRAN
  - GRAN_BIOMA
  - BIOMA_PREL
  - BIOMA_IAvH
  - ECOS_SINTE
  - ECOS_GENER
  - UNIDAD_SIN
  - CLIMA
  - PAISAJE
  - RELIEVE
  - SUELOS
  - AMB_EDAFOG
  - DESC_AMB_E
  - COBERTURA
  - UNI_BIOTIC
  - ANFIBIOS
  - AVES
  - MAGNOLIOPS
  - MAMIFEROS
  - REPTILES
  - NOMAH
  - NOMZH
  - NOMSZH
  - IPHE_CATEGORIA
  - IUEA_CATEGORIA
  - IARC_CATEGORIA
  - IUA_MEDIO_CAREGORIA
  - IUA_sECO_CATEGORIA
  - CATIACAL_M
  - CIACAL_S
  - cat
  - IVH_MEDIO_CATEGORIA
  - IVH_SECO_CATEGORIA
  - UCSuelo
  - S_UC
  - S_UC_FASE
  - OTRAS_FA_1
  - PENDIENT_1
  - EROSION_1
  - S_CLIMA
  - CLIMA_1
  - S_PAISAJE
  - PAISAJE_1
  - TIPO_RELIE
  - MATERIAL_P
  - SUBGRUPO
  - PERFILES
  - PORCENTAJE
  - PROFUNDIDA
  - TEXTURA
  - FERTILIDAD
  - ACIDEZ
  - DRENAJE
  - HUMEDAD
  - ALUMINIO
  - SALINIDAD_1
  - SODICIDAD
  - SATURACION
  - CALCAREO
  - Significad
  - layer
  - leyenda
  - CLAS_UPRA
  - FA
  - COBERTURAS_CON_USO_AGRO
  - AF
  - rango_precios_var_dependiente

qual_mappings:
  Attrited Customer: 1
  Existing Customer: 0
